In [1]:
#ANDMETE SAAMINE 

#laeme alla vajalikud moodulid
import numpy as np
import pandas as pd

#laeme alla andmed csv-st, mille nimi on spotify_dataset
andmed = pd.read_csv("spotify_dataset.csv") 

#võtame andmetest vaid need tulbad, mida kasutame koodis
uus = andmed[["Highest Charting Position", "Number of Times Charted", "Streams", "Artist Followers", "Popularity", "Danceability", "Energy", "Loudness", "Speechiness", "Acousticness", "Liveness", "Tempo", "Duration (ms)", "Valence"]]

#võtame ära read, kus on tühikud ehk kus andmeid pole
uus = uus[(uus["Highest Charting Position"]!=" ") & (uus["Number of Times Charted"]!=" ") & (uus["Artist Followers"]!=" ") & (uus["Popularity"]!=" ") & (uus["Danceability"]!=" ")& (uus["Energy"]!=" ")& (uus["Loudness"]!=" ") & (uus["Speechiness"]!=" ") & (uus["Acousticness"]!=" ")  & (uus[ "Liveness"]!=" ") & (uus["Tempo"]!=" ") & (uus["Duration (ms)"]!=" ") & (uus["Valence"]!=" ")] 

#võtame streamide arvus komad vahepealt ära
uus["Streams"] = uus['Streams'].str.replace(",","") 

#teeme kõik väärtused floatiks ehk komadega arvuks
uus = uus.astype(float)

In [2]:
#TREENIMISE JA TESTMISE GRUPPIDE TEGEMINE

#impordime tegevuseks vajaliku mooduli
from sklearn.model_selection import train_test_split

#X väärtuseks paneme kõik tulbad peale "Streams", mida kasutatakse ennustuse tegemiseks
X = uus[["Highest Charting Position", "Number of Times Charted", "Artist Followers", "Popularity", "Danceability", "Energy", "Loudness", "Speechiness", "Acousticness", "Liveness", "Tempo", "Duration (ms)", "Valence"]] # Mean squarred error (MSE): 7609495144579.66 Coefficient of determination (R2): 0.07 

# y väärtuseks tuleb ennustatav suurus
y = uus[["Streams"]]

#jaotame anded X ja y treenimise ja testmise gruppidesse
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1) 

#kuvame treenimise grupi streamid
y_train

        Streams
402   5198209.0
964   4351784.0
1309  5411302.0
1138  6069544.0
121   6242863.0
...         ...
721   5698275.0
914   4982232.0
1105  4627942.0
237   6731106.0
1070  4543863.0

[1236 rows x 1 columns]

In [3]:
#kuvame treenimise gruppide suuruse
y_train.shape, X_train.shape

((1236, 1), (1236, 13))

In [4]:
#kuvame testimise gruppide suuruse
X_test.shape, y_test.shape

((309, 13), (309, 1))

In [5]:
#TREENING GRUPIGA TREENIMINE

#impordime vajaliku mooduli
from sklearn.ensemble import RandomForestClassifier

#mooduli treenimine kasutades treening gruppe
model = RandomForestClassifier(n_estimators = 35) 
model.fit(X_train, y_train)

<ipython-input-5-2309dbc136d2>:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=35)

In [6]:
#ENNUSTAME STREAMIDE ARVU
y_pred = model.predict(X_test)
y_pred = y_pred.reshape(309,1)
#kuvame ennustused
y_pred

array([[ 4897374.],
       [ 5210780.],
       [ 4926802.],
       [ 4596162.],
       [ 4924533.],
       [ 5063181.],
       [ 4838067.],
       [ 4364166.],
       [ 4933462.],
       [ 5576844.],
       [ 5430260.],
       [ 6635109.],
       [ 4383521.],
       [ 4971559.],
       [ 4887204.],
       [ 4361970.],
       [ 6442626.],
       [ 5652272.],
       [11477024.],
       [ 5928329.],
       [ 4912914.],
       [ 5934464.],
       [ 5324545.],
       [ 5547939.],
       [ 4833081.],
       [ 6108393.],
       [10941573.],
       [ 4593449.],
       [ 5929516.],
       [ 4594248.],
       [ 4978899.],
       [ 5246577.],
       [ 4620876.],
       [ 5269757.],
       [ 7932101.],
       [ 5166847.],
       [ 4432210.],
       [ 4966878.],
       [ 4980571.],
       [ 4405338.],
       [ 5259503.],
       [ 5528508.],
       [ 4701388.],
       [ 5816739.],
       [ 5068972.],
       [ 4433384.],
       [ 4914682.],
       [10941573.],
       [ 6068816.],
       [ 5576844.],
       [14174752.],
       [ 4898520.],
       [13810722.],
       [ 4473968.],
       [ 4473968.],
       [ 5273046.],
       [ 5912784.],
       [ 6503281.],
       [ 5380517.],
       [ 5186567.],
       [ 4966878.],
       [ 5386512.],
       [ 5044853.],
       [ 5052801.],
       [ 4737306.],
       [ 5236560.],
       [14582001.],
       [ 6111108.],
       [ 4402281.],
       [ 5594561.],
       [ 7064003.],
       [ 5860405.],
       [ 6935400.],
       [ 4867723.],
       [ 4761908.],
       [ 4593343.],
       [ 5445204.],
       [ 4764355.],
       [ 5831357.],
       [ 4394985.],
       [ 5434180.],
       [ 5098581.],
       [ 4618744.],
       [ 4352767.],
       [ 4685894.],
       [ 5186141.],
       [ 4598325.],
       [ 4569978.],
       [ 8109572.],
       [ 4727415.],
       [ 4991751.],
       [ 5154955.],
       [ 5420003.],
       [ 4320116.],
       [11477024.],
       [ 5204983.],
       [ 5013450.],
       [ 7244853.],
       [22062812.],
       [ 4586236.],
       [ 5705999.],
       [ 5171235.],
       [ 4912914.],
       [ 5018005.],
       [ 4773792.],
       [ 9624871.],
       [ 6007011.],
       [ 6819838.],
       [ 4761286.],
       [ 4745752.],
       [ 4685894.],
       [ 5420003.],
       [ 4618744.],
       [ 9266945.],
       [ 4732292.],
       [ 9129562.],
       [ 5547939.],
       [ 4609858.],
       [ 5922748.],
       [ 5705999.],
       [ 4620876.],
       [ 4429092.],
       [ 7292247.],
       [ 5368759.],
       [ 4433384.],
       [ 4980155.],
       [ 6107499.],
       [ 4553544.],
       [ 6068816.],
       [ 4823401.],
       [ 4745568.],
       [ 6935400.],
       [ 5120753.],
       [ 8977336.],
       [ 6083338.],
       [ 4899099.],
       [ 4594248.],
       [ 8093413.],
       [ 9781153.],
       [ 9260007.],
       [ 5949270.],
       [ 5312936.],
       [ 4751756.],
       [ 4480780.],
       [ 5135380.],
       [ 5141640.],
       [ 4896939.],
       [ 4305034.],
       [ 5390363.],
       [11380679.],
       [ 5186567.],
       [ 4572706.],
       [ 4846549.],
       [ 7536851.],
       [ 4627026.],
       [ 9266945.],
       [ 4761286.],
       [ 5422082.],
       [ 6566059.],
       [ 4463865.],
       [ 9548924.],
       [ 5422082.],
       [ 4954292.],
       [ 5702636.],
       [ 4737291.],
       [ 5618268.],
       [14329162.],
       [ 4860714.],
       [ 4350496.],
       [ 4603243.],
       [ 4992405.],
       [ 9533583.],
       [ 4367368.],
       [ 7371935.],
       [48633449.],
       [ 5831357.],
       [ 5235088.],
       [ 5103014.],
       [ 4761155.],
       [ 5112180.],
       [ 5321544.],
       [ 4745568.],
       [ 5266625.],
       [ 4334669.],
       [ 6464206.],
       [ 8102107.],
       [ 5774770.],
       [ 5834918.],
       [ 4599408.],
       [ 5464816.],
       [ 4828004.],
       [ 5004752.],
       [ 7762934.],
       [ 5113459.],
       [ 8115520.],
       [ 4971559.],
       [ 5112244.],
       [ 5436286.],
       [ 5145493.],
       [ 5323062.],
       [ 4727923.],
       [ 5215973.],
       [ 4616034.],
       [ 4848222.],
       [ 4463865.],
       [ 4580123.],
       [ 5018005.],
       [ 5487774.],
       [ 4510218.],
       [ 5051338.],
       [ 4911995.],
       [ 5016125.],
       [ 4877753.],
       [ 8813922.],
       [ 5436286.],
       [ 5912784.],
       [ 4900492.],
       [ 5063181.],
       [ 5487774.],
       [ 4488125.],
       [ 4874960.],
       [ 4940701.],
       [18053141.],
       [ 4901559.],
       [ 4341050.],
       [ 5026961.],
       [ 4609169.],
       [ 5101640.],
       [ 4884909.],
       [ 7182262.],
       [ 7464020.],
       [ 4745568.],
       [ 4863053.],
       [ 5137482.],
       [ 9048966.],
       [ 5103863.],
       [ 4553544.],
       [ 4468668.],
       [10024729.],
       [ 4796365.],
       [ 9325928.],
       [ 6988886.],
       [ 4397385.],
       [ 5201322.],
       [ 4380308.],
       [ 5018005.],
       [ 5420003.],
       [ 4299334.],
       [ 4537762.],
       [ 5415044.],
       [ 5079657.],
       [ 4432210.],
       [ 4998044.],
       [ 5054319.],
       [ 4822090.],
       [ 6029118.],
       [ 4948563.],
       [ 5103194.],
       [ 5528508.],
       [ 5104422.],
       [ 5656775.],
       [ 5422082.],
       [ 5588217.],
       [ 5674945.],
       [ 5060764.],
       [ 4954899.],
       [ 5088848.],
       [ 5368759.],
       [ 9266945.],
       [ 6268542.],
       [ 4701388.],
       [ 4641393.],
       [ 5115153.],
       [ 4384527.],
       [ 9325928.],
       [ 6066001.],
       [ 4887204.],
       [ 4609169.],
       [ 4852004.],
       [ 8102107.],
       [ 6697067.],
       [ 4463865.],
       [ 4898167.],
       [ 4920218.],
       [ 4621205.],
       [ 5249342.],
       [ 5415044.],
       [ 6561188.],
       [ 6540577.],
       [ 5848466.],
       [ 4313625.],
       [ 4891989.],
       [ 9266945.],
       [ 5535339.],
       [ 4732292.],
       [ 5375944.],
       [ 8109572.],
       [ 6540577.],
       [ 5622565.],
       [ 4904772.],
       [ 4628159.],
       [ 4813796.],
       [ 5867746.],
       [ 7717211.],
       [ 5068972.],
       [ 5878493.],
       [ 4906738.],
       [ 4396629.],
       [ 7292247.]])

In [7]:
#kuvame streamide tegelikud väärtused
y_test

        Streams
1323  4787180.0
483   5418816.0
641   6404964.0
1241  5291167.0
1272  5307288.0
...         ...
946   4391666.0
809   5226264.0
771   5308945.0
1550  4676857.0
1456  5823422.0

[309 rows x 1 columns]

In [8]:
#arvutame ennustuse ja tegeliku streamide arvu vahe absoluutväärtuses ja kuvame selle
vahe = abs(y_pred - y_test) 
vahe = list(vahe["Streams"])
vahe

[110194.0,
 208036.0,
 1478162.0,
 695005.0,
 382755.0,
 93519.0,
 848914.0,
 841936.0,
 42258.0,
 497257.0,
 443961.0,
 1814448.0,
 2267904.0,
 103939.0,
 4002.0,
 811208.0,
 1036992.0,
 1056834.0,
 1635026.0,
 771566.0,
 909352.0,
 3105054.0,
 2767209.0,
 537760.0,
 149811.0,
 532335.0,
 6045052.0,
 731998.0,
 1015087.0,
 3624175.0,
 257831.0,
 5466071.0,
 82796.0,
 110549.0,
 706259.0,
 1989315.0,
 124690.0,
 50018.0,
 115487.0,
 1075384.0,
 177270.0,
 926172.0,
 248569.0,
 190802.0,
 750200.0,
 171419.0,
 93469.0,
 5862245.0,
 1153736.0,
 874727.0,
 5239334.0,
 336125.0,
 8013744.0,
 1327671.0,
 491362.0,
 3291729.0,
 986941.0,
 1098342.0,
 76131.0,
 1749738.0,
 2945521.0,
 37485.0,
 415770.0,
 28999.0,
 135103.0,
 3126268.0,
 9489751.0,
 5442738.0,
 2211791.0,
 1209413.0,
 2149591.0,
 648278.0,
 395548.0,
 1370628.0,
 617063.0,
 399002.0,
 810750.0,
 361351.0,
 926956.0,
 439273.0,
 610143.0,
 489223.0,
 20450.0,
 759805.0,
 367819.0,
 65777.0,
 576112.0,
 58794.0,
 3027009.0,
 727579.0,
 843509.0,
 348947.0,
 571049.0,
 354416.0,
 3962170.0,
 288777.0,
 468940.0,
 392773.0,
 12634318.0,
 2399156.0,
 3803782.0,
 731445.0,
 157437.0,
 145628.0,
 571070.0,
 258118.0,
 1143101.0,
 1758935.0,
 651717.0,
 1822003.0,
 113978.0,
 523848.0,
 54413.0,
 4646107.0,
 418722.0,
 3198320.0,
 427946.0,
 533124.0,
 934694.0,
 311945.0,
 80656.0,
 3022360.0,
 2413344.0,
 890074.0,
 707663.0,
 324883.0,
 926319.0,
 2012555.0,
 1652332.0,
 135492.0,
 375719.0,
 1961463.0,
 532689.0,
 4014387.0,
 1517961.0,
 105363.0,
 5294949.0,
 1849402.0,
 3064800.0,
 358310.0,
 1318698.0,
 203898.0,
 1281179.0,
 549701.0,
 842371.0,
 2222273.0,
 465878.0,
 5347365.0,
 353239.0,
 5912596.0,
 310329.0,
 534378.0,
 331558.0,
 7887150.0,
 452831.0,
 3796798.0,
 106894.0,
 2738452.0,
 1284070.0,
 704242.0,
 4602989.0,
 2600691.0,
 260919.0,
 149746.0,
 459344.0,
 975984.0,
 2579755.0,
 243492.0,
 1115665.0,
 732065.0,
 394999.0,
 4049955.0,
 1544925.0,
 1931682.0,
 10833993.0,
 448232.0,
 1217404.0,
 653569.0,
 73691.0,
 47943.0,
 60647.0,
 72401.0,
 828364.0,
 482033.0,
 1389721.0,
 1697594.0,
 1209492.0,
 723850.0,
 272669.0,
 1220306.0,
 252601.0,
 1655567.0,
 645587.0,
 211499.0,
 3721588.0,
 271407.0,
 719207.0,
 434059.0,
 13403.0,
 897452.0,
 214622.0,
 354595.0,
 2449026.0,
 5627990.0,
 911584.0,
 235219.0,
 3866278.0,
 280588.0,
 280015.0,
 92184.0,
 237337.0,
 4619494.0,
 2508111.0,
 456095.0,
 308550.0,
 672112.0,
 384439.0,
 383233.0,
 1568144.0,
 951521.0,
 454773.0,
 412890.0,
 4089573.0,
 3596.0,
 577586.0,
 1007320.0,
 532043.0,
 744844.0,
 211715.0,
 119119.0,
 4802970.0,
 290462.0,
 315088.0,
 472429.0,
 3964331.0,
 818912.0,
 5504759.0,
 773429.0,
 4846239.0,
 247282.0,
 3725060.0,
 1620181.0,
 2956410.0,
 97571.0,
 1047226.0,
 1126731.0,
 5367162.0,
 2565895.0,
 410018.0,
 1979560.0,
 2984704.0,
 151265.0,
 173561.0,
 149045.0,
 571699.0,
 1535775.0,
 115941.0,
 86229.0,
 1987258.0,
 54559.0,
 776804.0,
 26598.0,
 392375.0,
 767506.0,
 461998.0,
 1049940.0,
 243589.0,
 321007.0,
 2409137.0,
 1279971.0,
 326940.0,
 1088688.0,
 1295110.0,
 119777.0,
 3096612.0,
 1889918.0,
 247207.0,
 320227.0,
 82386.0,
 984872.0,
 1003219.0,
 998468.0,
 999816.0,
 232688.0,
 75322.0,
 263305.0,
 3444124.0,
 1083133.0,
 1354223.0,
 1425561.0,
 3822622.0,
 587418.0,
 4180563.0,
 1058385.0,
 192422.0,
 3102574.0,
 3414481.0,
 166524.0,
 341755.0,
 2460281.0,
 733510.0,
 502031.0,
 936288.0,
 2499065.0,
 677306.0,
 652229.0,
 402207.0,
 280228.0,
 1468825.0]

In [9]:
#arvutame vahede absoluutväärtused kokku
vahe_kokku = 0
for i in vahe:
    vahe_kokku += i
vahe_kokku

422350946.0

In [11]:
#kuvame keskmine vahe
keskmine_vahe = vahe_kokku // 309
print("Keskmine vahe on: " + str(keskmine_vahe))

Keskmine vahe on: 1366831.0

In [12]:
#TÄPSUSE HINDAMINE

#vaatame igat arvutatud vahet ja jagame vastavalt suuruse järgi selle gruppidesse, et näha kui täpselt ennustati streamide arvu
loendur1 = 0 
loendur2 = 0 
loendur3 = 0 
loendur4 = 0 
loendur5 = 0 
loendur6 = 0 
loendur7 = 0 
loendur8 = 0 
loendur9 = 0 
loendur10 = 0 
loendur11 = 0
loendur12 = 0
loendur13 = 0
loendur14 = 0
loendur15 = 0
loendur16 = 0
loendur17 = 0
loendur18 = 0
loendur19 = 0
loendur = 0

for i in vahe:
    if float(i) < 10000:
        loendur1 += 1
    elif i < 100000:
        loendur2 += 1
    elif i < 200000:
        loendur3 += 1    
    elif i < 300000:
        loendur4 += 1
    elif i < 400000:
        loendur5 += 1
    elif i < 500000:
        loendur6 += 1
    elif i < 600000:
        loendur7 += 1
    elif i < 700000:
        loendur8 += 1
    elif i < 800000:
        loendur9 += 1
    elif i < 900000:
        loendur10 += 1
    elif i < 1000000:
        loendur11 += 1
    elif i < 2000000:
        loendur12 += 1
    elif i < 3000000:
        loendur13 += 1
    elif i < 4000000:
        loendur14 += 1
    elif i < 5000000:
        loendur15 += 1
    elif i < 6000000:
        loendur16 += 1
    elif i < 7000000:
        loendur17 += 1
    elif i < 8000000:
        loendur18 += 1
    elif i < 9000000:
        loendur19 += 1
    elif i >= 900000:
        loendur += 1

#kuvame mitu ennustust olid erinevates vahemikes
print("Vahe väärtus vahemikus 0-10000: ", str(loendur1))
print("Vahe väärtus vahemikus 10000-100000: ", str(loendur2))
print("Vahe väärtus vahemikus 100000-200000: ", str(loendur3))
print("Vahe väärtus vahemikus 200000-300000: ", str(loendur4))
print("Vahe väärtus vahemikus 300000-400000: ", str(loendur5))
print("Vahe väärtus vahemikus 400000-500000: ", str(loendur6))
print("Vahe väärtus vahemikus 500000-600000: ", str(loendur7))
print("Vahe väärtus vahemikus 600000-700000: ", str(loendur8))
print("Vahe väärtus vahemikus 700000-800000: ", str(loendur9))
print("Vahe väärtus vahemikus 800000-900000: ", str(loendur10))
print("Vahe väärtus vahemikus 900000-1000000: ", str(loendur11))
print("Vahe väärtus vahemikus 1000000-2000000: ", str(loendur12))
print("Vahe väärtus vahemikus 2000000-3000000: ", str(loendur13))
print("Vahe väärtus vahemikus 3000000-4000000: ", str(loendur14))
print("Vahe väärtus vahemikus 4000000-5000000: ", str(loendur15))
print("Vahe väärtus vahemikus 5000000-6000000: ", str(loendur16))
print("Vahe väärtus vahemikus 6000000-7000000: ", str(loendur17))
print("Vahe väärtus vahemikus 7000000-8000000: ", str(loendur18))
print("Vahe väärtus vahemikus 8000000-9000000: ", str(loendur19))
print("Vahe väärtus vahemikus 9000000+: ", str(loendur))

Vahe väärtus vahemikus 0-10000:  2
Vahe väärtus vahemikus 10000-100000:  25
Vahe väärtus vahemikus 100000-200000:  25
Vahe väärtus vahemikus 200000-300000:  25
Vahe väärtus vahemikus 300000-400000:  27
Vahe väärtus vahemikus 400000-500000:  22
Vahe väärtus vahemikus 500000-600000:  15
Vahe väärtus vahemikus 600000-700000:  10
Vahe väärtus vahemikus 700000-800000:  17
Vahe väärtus vahemikus 800000-900000:  11
Vahe väärtus vahemikus 900000-1000000:  13
Vahe väärtus vahemikus 1000000-2000000:  52
Vahe väärtus vahemikus 2000000-3000000:  20
Vahe väärtus vahemikus 3000000-4000000:  20
Vahe väärtus vahemikus 4000000-5000000:  9
Vahe väärtus vahemikus 5000000-6000000:  10
Vahe väärtus vahemikus 6000000-7000000:  1
Vahe väärtus vahemikus 7000000-8000000:  1
Vahe väärtus vahemikus 8000000-9000000:  1
Vahe väärtus vahemikus 9000000+:  3

In [14]:
#kuvame mitu korda oli ennustuse ja tegliku arvu vahe alla 1000
print("Vahe alla 10000 oli: ", str(loendur1))

Vahe alla 10000 oli:  2